### ISSUE TITLE
Monkey patch DDP callbacks to bubble up errors to Cucumber

### ISSUE THREAD

**Issue by samhatoum** [xolvio/cuke-monkey#1]
currently you have to write:

```
this.Given(/^I have created a settings file with the title "([^"]*)"$/, function (title, callback) {
  this.ddp.call('updateTitle', [title], function(err, res) {
    if (err) { 
      callback.fail(err);
    } else {
      callback();
    }
  });
});
```

This would be much cleaner this way:
```
  this.ddp.call('updateTitle', [title], callback);
```

And can be achieved by monkey-patching `global.ddp.call`

**Comment by Sanjo** [comment]
I'd like to see a promise version of ddp.call and ddp.apply. So you don't pass a callback at all. E.g. `

```javascript
this.ddp.callAsync('updateTitle', [title])
  .then(function () {
    // Do something else
  })
  .then(callback, callback) // If Cucumber supports Promises this can be removed
```

**Comment by dandv** [comment]
Would the newer DDP from @pscanf (author of [Asteroid](https://github.com/mondora/asteroid)) be a better choice?

https://github.com/mondora/ddp.js

**Comment by samhatoum** [comment]
Oh nice find. Didn't know about this one. I've always disliked the DDP client we currently use and this new one has tests which is nice.

I think with the sync version this problem has gone away (pending testing). I'll keep this issue open until we decide if it's worth switching to DDP.js

**Comment by Sanjo** [comment]
We have solved this issue by forking the ddp npm package. https://github.com/mondora/ddp.js only provides the lower level DDP API. So we would need to create the high level API that Meteor provides on top of it. Because our current DDP package seems to work well, I don't see a reason for it right now.
